apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
spec:
  selector:
    app: nats
  ports:
  - name: nats
    port: 4222
    targetPort: 4222
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: bitnami/nats:latest
        ports:
        - name: nats
          containerPort: 4222
        env:
        - name: NATS_USER
          value: nats
        - name: NATS_PASSWORD
          value: nats
        - name: NATS_HTTP_PORT
          value: "8222"
        - name: NATS_CLUSTER_PORT
          value: "6222"
        - name: NATS_PORT
          value: "4222"
        - name: NATS_LOG_LEVEL
          value: "debug"

